<?php

namespace Jlay\Bundle\BlogBundle\Entity;

/**
 * SnippetRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SnippetRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * Select snippets by Path
     *
     * @return array
     */
    public function findAllPath(){

        return $this->getEntityManager()
            ->createQuery('SELECT DISTINCT p.path FROM JlayBlogBundle:Snippet p ORDER BY p.path ASC')
            ->getResult();
    }
}
